FROM golang:1.25 AS build

WORKDIR /go/src/app
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 go build -o /go/bin/client-telegram -ldflags '-w -s' cmd/client-telegram/main.go


FROM gcr.io/distroless/static AS production
COPY --from=build /go/bin/client-telegram /client-telegram
ENTRYPOINT ["/client-telegram"]
